### ISSUE TITLE
document_exit undefined for older Firefox

### ISSUE THREAD

**Issue by matthiasprieth** [chrisdickinson/fullscreen#4]
Tested with Firefox 36.04:
`var document_exit = .....` was undefined.

So `document_exit.call(doc);` raised an error.

**Comment by dhritzkiv** [comment]
+1

Looks like the problem comes from trying to call `mozExitFullScreen` or `mozExitFullscreen` when it should be `mozCancelFullScreen`, [as per MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/mozCancelFullScreen). Looks like `mozExitFull*` never existed?

I'll fork, fix, and PR this shortly.

**Comment by dhritzkiv** [comment]
Looks like this is already addressed in PR #2. Hopefully merged soon.

**Comment by matthiasprieth** [comment]
Awesome thanks!
